# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockDataWidget_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_stockDataWidget(object):
    def setupUi(self, stockDataWidget):
        stockDataWidget.setObjectName(_fromUtf8("stockDataWidget"))
        stockDataWidget.resize(739, 517)
        self.verticalLayout = QtGui.QVBoxLayout(stockDataWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(stockDataWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabHistoricalQuotation = QtGui.QWidget()
        self.tabHistoricalQuotation.setObjectName(_fromUtf8("tabHistoricalQuotation"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabHistoricalQuotation)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labDataSource = QtGui.QLabel(self.tabHistoricalQuotation)
        self.labDataSource.setObjectName(_fromUtf8("labDataSource"))
        self.gridLayout_2.addWidget(self.labDataSource, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkBoxSH = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSH.setObjectName(_fromUtf8("chkBoxSH"))
        self.buttonGroup = QtGui.QButtonGroup(stockDataWidget)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.chkBoxSH)
        self.gridLayout.addWidget(self.chkBoxSH, 0, 0, 1, 1)
        self.chkBoxSZ = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSZ.setObjectName(_fromUtf8("chkBoxSZ"))
        self.buttonGroup.addButton(self.chkBoxSZ)
        self.gridLayout.addWidget(self.chkBoxSZ, 0, 1, 1, 1)
        self.chkBoxHS300 = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxHS300.setObjectName(_fromUtf8("chkBoxHS300"))
        self.buttonGroup.addButton(self.chkBoxHS300)
        self.gridLayout.addWidget(self.chkBoxHS300, 0, 2, 1, 1)
        self.chkBoxSZ50 = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSZ50.setObjectName(_fromUtf8("chkBoxSZ50"))
        self.buttonGroup.addButton(self.chkBoxSZ50)
        self.gridLayout.addWidget(self.chkBoxSZ50, 0, 3, 1, 1)
        self.chkBoxZXB = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxZXB.setObjectName(_fromUtf8("chkBoxZXB"))
        self.buttonGroup.addButton(self.chkBoxZXB)
        self.gridLayout.addWidget(self.chkBoxZXB, 1, 0, 1, 1)
        self.chkBoxCYB = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxCYB.setObjectName(_fromUtf8("chkBoxCYB"))
        self.buttonGroup.addButton(self.chkBoxCYB)
        self.gridLayout.addWidget(self.chkBoxCYB, 1, 1, 1, 1)
        self.chkBoxStockCode = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxStockCode.setObjectName(_fromUtf8("chkBoxStockCode"))
        self.buttonGroup.addButton(self.chkBoxStockCode)
        self.gridLayout.addWidget(self.chkBoxStockCode, 1, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.labStockCodeForHistoricalQuotation = QtGui.QLabel(self.tabHistoricalQuotation)
        self.labStockCodeForHistoricalQuotation.setObjectName(_fromUtf8("labStockCodeForHistoricalQuotation"))
        self.gridLayout_2.addWidget(self.labStockCodeForHistoricalQuotation, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditStockCodeForHistoricalQuotation = QtGui.QLineEdit(self.tabHistoricalQuotation)
        self.lineEditStockCodeForHistoricalQuotation.setObjectName(_fromUtf8("lineEditStockCodeForHistoricalQuotation"))
        self.horizontalLayout_2.addWidget(self.lineEditStockCodeForHistoricalQuotation)
        self.chkBoxBulkModeForHistoricalQuotation = QtGui.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxBulkModeForHistoricalQuotation.setObjectName(_fromUtf8("chkBoxBulkModeForHistoricalQuotation"))
        self.horizontalLayout_2.addWidget(self.chkBoxBulkModeForHistoricalQuotation)
        self.btnBulkModeForHistoricalQuotation = QtGui.QPushButton(self.tabHistoricalQuotation)
        self.btnBulkModeForHistoricalQuotation.setObjectName(_fromUtf8("btnBulkModeForHistoricalQuotation"))
        self.horizontalLayout_2.addWidget(self.btnBulkModeForHistoricalQuotation)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.labStartTimeForHistoricalQuotation = QtGui.QLabel(self.tabHistoricalQuotation)
        self.labStartTimeForHistoricalQuotation.setObjectName(_fromUtf8("labStartTimeForHistoricalQuotation"))
        self.gridLayout_2.addWidget(self.labStartTimeForHistoricalQuotation, 2, 0, 1, 1)
        self.lineEditStartTimeForHistoricalQuotation = LineEdit(self.tabHistoricalQuotation)
        self.lineEditStartTimeForHistoricalQuotation.setObjectName(_fromUtf8("lineEditStartTimeForHistoricalQuotation"))
        self.gridLayout_2.addWidget(self.lineEditStartTimeForHistoricalQuotation, 2, 1, 1, 1)
        self.labEndTimeForHistoricalQuotation = QtGui.QLabel(self.tabHistoricalQuotation)
        self.labEndTimeForHistoricalQuotation.setObjectName(_fromUtf8("labEndTimeForHistoricalQuotation"))
        self.gridLayout_2.addWidget(self.labEndTimeForHistoricalQuotation, 3, 0, 1, 1)
        self.lineEditEndTimeForHistoricalQuotation = LineEdit(self.tabHistoricalQuotation)
        self.lineEditEndTimeForHistoricalQuotation.setObjectName(_fromUtf8("lineEditEndTimeForHistoricalQuotation"))
        self.gridLayout_2.addWidget(self.lineEditEndTimeForHistoricalQuotation, 3, 1, 1, 1)
        self.labDataType = QtGui.QLabel(self.tabHistoricalQuotation)
        self.labDataType.setObjectName(_fromUtf8("labDataType"))
        self.gridLayout_2.addWidget(self.labDataType, 4, 0, 1, 1)
        self.comboBoxDataType = QtGui.QComboBox(self.tabHistoricalQuotation)
        self.comboBoxDataType.setObjectName(_fromUtf8("comboBoxDataType"))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.comboBoxDataType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxDataType, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.widgetHistoricalQuotation = QtGui.QWidget(self.tabHistoricalQuotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetHistoricalQuotation.sizePolicy().hasHeightForWidth())
        self.widgetHistoricalQuotation.setSizePolicy(sizePolicy)
        self.widgetHistoricalQuotation.setObjectName(_fromUtf8("widgetHistoricalQuotation"))
        self.verticalLayout_2.addWidget(self.widgetHistoricalQuotation)
        self.tabWidget.addTab(self.tabHistoricalQuotation, _fromUtf8(""))
        self.tabRehabilitationData = QtGui.QWidget()
        self.tabRehabilitationData.setObjectName(_fromUtf8("tabRehabilitationData"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabRehabilitationData)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labStockCodeForRehabilitationData = QtGui.QLabel(self.tabRehabilitationData)
        self.labStockCodeForRehabilitationData.setObjectName(_fromUtf8("labStockCodeForRehabilitationData"))
        self.gridLayout_3.addWidget(self.labStockCodeForRehabilitationData, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditStockCodeForRehabilitationData = QtGui.QLineEdit(self.tabRehabilitationData)
        self.lineEditStockCodeForRehabilitationData.setObjectName(_fromUtf8("lineEditStockCodeForRehabilitationData"))
        self.horizontalLayout_3.addWidget(self.lineEditStockCodeForRehabilitationData)
        self.chkBoxBulkModeForRehabilitationData = QtGui.QCheckBox(self.tabRehabilitationData)
        self.chkBoxBulkModeForRehabilitationData.setObjectName(_fromUtf8("chkBoxBulkModeForRehabilitationData"))
        self.horizontalLayout_3.addWidget(self.chkBoxBulkModeForRehabilitationData)
        self.btnBulkModeForRehabilitationData = QtGui.QPushButton(self.tabRehabilitationData)
        self.btnBulkModeForRehabilitationData.setObjectName(_fromUtf8("btnBulkModeForRehabilitationData"))
        self.horizontalLayout_3.addWidget(self.btnBulkModeForRehabilitationData)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.labStartTimeForRehabilitationData = QtGui.QLabel(self.tabRehabilitationData)
        self.labStartTimeForRehabilitationData.setObjectName(_fromUtf8("labStartTimeForRehabilitationData"))
        self.gridLayout_3.addWidget(self.labStartTimeForRehabilitationData, 1, 0, 1, 1)
        self.lineEditStartTimeForRehabilitationData = LineEdit(self.tabRehabilitationData)
        self.lineEditStartTimeForRehabilitationData.setObjectName(_fromUtf8("lineEditStartTimeForRehabilitationData"))
        self.gridLayout_3.addWidget(self.lineEditStartTimeForRehabilitationData, 1, 1, 1, 1)
        self.labEndTimeForRehabilitationData = QtGui.QLabel(self.tabRehabilitationData)
        self.labEndTimeForRehabilitationData.setObjectName(_fromUtf8("labEndTimeForRehabilitationData"))
        self.gridLayout_3.addWidget(self.labEndTimeForRehabilitationData, 2, 0, 1, 1)
        self.lineEditEndTimeForRehabilitationData = LineEdit(self.tabRehabilitationData)
        self.lineEditEndTimeForRehabilitationData.setObjectName(_fromUtf8("lineEditEndTimeForRehabilitationData"))
        self.gridLayout_3.addWidget(self.lineEditEndTimeForRehabilitationData, 2, 1, 1, 1)
        self.labRehabilitationType = QtGui.QLabel(self.tabRehabilitationData)
        self.labRehabilitationType.setObjectName(_fromUtf8("labRehabilitationType"))
        self.gridLayout_3.addWidget(self.labRehabilitationType, 3, 0, 1, 1)
        self.comboBoxRehabilitationType = QtGui.QComboBox(self.tabRehabilitationData)
        self.comboBoxRehabilitationType.setObjectName(_fromUtf8("comboBoxRehabilitationType"))
        self.comboBoxRehabilitationType.addItem(_fromUtf8(""))
        self.comboBoxRehabilitationType.addItem(_fromUtf8(""))
        self.comboBoxRehabilitationType.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBoxRehabilitationType, 3, 1, 1, 1)
        self.labIsMarketIndex = QtGui.QLabel(self.tabRehabilitationData)
        self.labIsMarketIndex.setObjectName(_fromUtf8("labIsMarketIndex"))
        self.gridLayout_3.addWidget(self.labIsMarketIndex, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkBoxYes = QtGui.QCheckBox(self.tabRehabilitationData)
        self.chkBoxYes.setObjectName(_fromUtf8("chkBoxYes"))
        self.buttonGroup_2 = QtGui.QButtonGroup(stockDataWidget)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.chkBoxYes)
        self.horizontalLayout_4.addWidget(self.chkBoxYes)
        self.chkBoxNo = QtGui.QCheckBox(self.tabRehabilitationData)
        self.chkBoxNo.setObjectName(_fromUtf8("chkBoxNo"))
        self.buttonGroup_2.addButton(self.chkBoxNo)
        self.horizontalLayout_4.addWidget(self.chkBoxNo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.widgetRehabilitationData = QtGui.QWidget(self.tabRehabilitationData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRehabilitationData.sizePolicy().hasHeightForWidth())
        self.widgetRehabilitationData.setSizePolicy(sizePolicy)
        self.widgetRehabilitationData.setObjectName(_fromUtf8("widgetRehabilitationData"))
        self.verticalLayout_3.addWidget(self.widgetRehabilitationData)
        self.tabWidget.addTab(self.tabRehabilitationData, _fromUtf8(""))
        self.tabRealTimeQuotes = QtGui.QWidget()
        self.tabRealTimeQuotes.setObjectName(_fromUtf8("tabRealTimeQuotes"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabRealTimeQuotes)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widgetRealTimeQuotes = QtGui.QWidget(self.tabRealTimeQuotes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRealTimeQuotes.sizePolicy().hasHeightForWidth())
        self.widgetRealTimeQuotes.setSizePolicy(sizePolicy)
        self.widgetRealTimeQuotes.setObjectName(_fromUtf8("widgetRealTimeQuotes"))
        self.verticalLayout_4.addWidget(self.widgetRealTimeQuotes)
        self.tabWidget.addTab(self.tabRealTimeQuotes, _fromUtf8(""))
        self.tabHistoricalTick = QtGui.QWidget()
        self.tabHistoricalTick.setObjectName(_fromUtf8("tabHistoricalTick"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabHistoricalTick)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labStockCodeForHistoricalTick = QtGui.QLabel(self.tabHistoricalTick)
        self.labStockCodeForHistoricalTick.setObjectName(_fromUtf8("labStockCodeForHistoricalTick"))
        self.gridLayout_4.addWidget(self.labStockCodeForHistoricalTick, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEditStockCodeForHistoricalTick = QtGui.QLineEdit(self.tabHistoricalTick)
        self.lineEditStockCodeForHistoricalTick.setObjectName(_fromUtf8("lineEditStockCodeForHistoricalTick"))
        self.horizontalLayout_6.addWidget(self.lineEditStockCodeForHistoricalTick)
        self.chkBoxBulkModeForHistoricalTick = QtGui.QCheckBox(self.tabHistoricalTick)
        self.chkBoxBulkModeForHistoricalTick.setObjectName(_fromUtf8("chkBoxBulkModeForHistoricalTick"))
        self.horizontalLayout_6.addWidget(self.chkBoxBulkModeForHistoricalTick)
        self.btnBulkModeForHistoricalTick = QtGui.QPushButton(self.tabHistoricalTick)
        self.btnBulkModeForHistoricalTick.setObjectName(_fromUtf8("btnBulkModeForHistoricalTick"))
        self.horizontalLayout_6.addWidget(self.btnBulkModeForHistoricalTick)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.labTickTimeForHistoricalTick = QtGui.QLabel(self.tabHistoricalTick)
        self.labTickTimeForHistoricalTick.setObjectName(_fromUtf8("labTickTimeForHistoricalTick"))
        self.gridLayout_4.addWidget(self.labTickTimeForHistoricalTick, 1, 0, 1, 1)
        self.lineEditTickTimeForHistoricalTick = LineEdit(self.tabHistoricalTick)
        self.lineEditTickTimeForHistoricalTick.setObjectName(_fromUtf8("lineEditTickTimeForHistoricalTick"))
        self.gridLayout_4.addWidget(self.lineEditTickTimeForHistoricalTick, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.widgetHistoricalTick = QtGui.QWidget(self.tabHistoricalTick)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetHistoricalTick.sizePolicy().hasHeightForWidth())
        self.widgetHistoricalTick.setSizePolicy(sizePolicy)
        self.widgetHistoricalTick.setObjectName(_fromUtf8("widgetHistoricalTick"))
        self.verticalLayout_5.addWidget(self.widgetHistoricalTick)
        self.tabWidget.addTab(self.tabHistoricalTick, _fromUtf8(""))
        self.tabRealTimeTick = QtGui.QWidget()
        self.tabRealTimeTick.setObjectName(_fromUtf8("tabRealTimeTick"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabRealTimeTick)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labDataSourceForRealTimeTick = QtGui.QLabel(self.tabRealTimeTick)
        self.labDataSourceForRealTimeTick.setObjectName(_fromUtf8("labDataSourceForRealTimeTick"))
        self.gridLayout_6.addWidget(self.labDataSourceForRealTimeTick, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.chkBoxSHForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxSHForRealTimeTick.setObjectName(_fromUtf8("chkBoxSHForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxSHForRealTimeTick, 0, 0, 1, 1)
        self.chkBoxSZForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxSZForRealTimeTick.setObjectName(_fromUtf8("chkBoxSZForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxSZForRealTimeTick, 0, 1, 1, 1)
        self.chkBoxHS300ForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxHS300ForRealTimeTick.setObjectName(_fromUtf8("chkBoxHS300ForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxHS300ForRealTimeTick, 0, 2, 1, 1)
        self.chkBoxSZ50ForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxSZ50ForRealTimeTick.setObjectName(_fromUtf8("chkBoxSZ50ForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxSZ50ForRealTimeTick, 0, 3, 1, 1)
        self.chkBoxZXBForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxZXBForRealTimeTick.setObjectName(_fromUtf8("chkBoxZXBForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxZXBForRealTimeTick, 1, 0, 1, 1)
        self.chkBoxCYBForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxCYBForRealTimeTick.setObjectName(_fromUtf8("chkBoxCYBForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxCYBForRealTimeTick, 1, 1, 1, 1)
        self.chkBoxStockCodeForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxStockCodeForRealTimeTick.setObjectName(_fromUtf8("chkBoxStockCodeForRealTimeTick"))
        self.gridLayout_5.addWidget(self.chkBoxStockCodeForRealTimeTick, 1, 2, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.labStockCodeForRealTimeTick = QtGui.QLabel(self.tabRealTimeTick)
        self.labStockCodeForRealTimeTick.setObjectName(_fromUtf8("labStockCodeForRealTimeTick"))
        self.gridLayout_6.addWidget(self.labStockCodeForRealTimeTick, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEditStockCodeForRealTimeTick = QtGui.QLineEdit(self.tabRealTimeTick)
        self.lineEditStockCodeForRealTimeTick.setObjectName(_fromUtf8("lineEditStockCodeForRealTimeTick"))
        self.horizontalLayout_5.addWidget(self.lineEditStockCodeForRealTimeTick)
        self.chkBoxBulkModeForRealTimeTick = QtGui.QCheckBox(self.tabRealTimeTick)
        self.chkBoxBulkModeForRealTimeTick.setObjectName(_fromUtf8("chkBoxBulkModeForRealTimeTick"))
        self.horizontalLayout_5.addWidget(self.chkBoxBulkModeForRealTimeTick)
        self.btnBulkModeForRealTimeTick = QtGui.QPushButton(self.tabRealTimeTick)
        self.btnBulkModeForRealTimeTick.setObjectName(_fromUtf8("btnBulkModeForRealTimeTick"))
        self.horizontalLayout_5.addWidget(self.btnBulkModeForRealTimeTick)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.widgetRealTimeTick = QtGui.QWidget(self.tabRealTimeTick)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRealTimeTick.sizePolicy().hasHeightForWidth())
        self.widgetRealTimeTick.setSizePolicy(sizePolicy)
        self.widgetRealTimeTick.setObjectName(_fromUtf8("widgetRealTimeTick"))
        self.verticalLayout_6.addWidget(self.widgetRealTimeTick)
        self.tabWidget.addTab(self.tabRealTimeTick, _fromUtf8(""))
        self.tabSameDayHistoricalTick = QtGui.QWidget()
        self.tabSameDayHistoricalTick.setObjectName(_fromUtf8("tabSameDayHistoricalTick"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabSameDayHistoricalTick)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labStockCodeForSameDayHistoricalTick = QtGui.QLabel(self.tabSameDayHistoricalTick)
        self.labStockCodeForSameDayHistoricalTick.setObjectName(_fromUtf8("labStockCodeForSameDayHistoricalTick"))
        self.horizontalLayout_7.addWidget(self.labStockCodeForSameDayHistoricalTick)
        self.lineEditStockCodeForSameDayHistoricalTick = QtGui.QLineEdit(self.tabSameDayHistoricalTick)
        self.lineEditStockCodeForSameDayHistoricalTick.setObjectName(_fromUtf8("lineEditStockCodeForSameDayHistoricalTick"))
        self.horizontalLayout_7.addWidget(self.lineEditStockCodeForSameDayHistoricalTick)
        self.chkBoxBulkModeForSameDayHistoricalTick = QtGui.QCheckBox(self.tabSameDayHistoricalTick)
        self.chkBoxBulkModeForSameDayHistoricalTick.setObjectName(_fromUtf8("chkBoxBulkModeForSameDayHistoricalTick"))
        self.horizontalLayout_7.addWidget(self.chkBoxBulkModeForSameDayHistoricalTick)
        self.btnBulkModeForSameDayHistoricalTick = QtGui.QPushButton(self.tabSameDayHistoricalTick)
        self.btnBulkModeForSameDayHistoricalTick.setObjectName(_fromUtf8("btnBulkModeForSameDayHistoricalTick"))
        self.horizontalLayout_7.addWidget(self.btnBulkModeForSameDayHistoricalTick)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.widgetSameDayHistoricalTick = QtGui.QWidget(self.tabSameDayHistoricalTick)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSameDayHistoricalTick.sizePolicy().hasHeightForWidth())
        self.widgetSameDayHistoricalTick.setSizePolicy(sizePolicy)
        self.widgetSameDayHistoricalTick.setObjectName(_fromUtf8("widgetSameDayHistoricalTick"))
        self.verticalLayout_7.addWidget(self.widgetSameDayHistoricalTick)
        self.tabWidget.addTab(self.tabSameDayHistoricalTick, _fromUtf8(""))
        self.tabMarketIndexList = QtGui.QWidget()
        self.tabMarketIndexList.setObjectName(_fromUtf8("tabMarketIndexList"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabMarketIndexList)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.widgetMarketIndexList = QtGui.QWidget(self.tabMarketIndexList)
        self.widgetMarketIndexList.setObjectName(_fromUtf8("widgetMarketIndexList"))
        self.gridLayout_8.addWidget(self.widgetMarketIndexList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMarketIndexList, _fromUtf8(""))
        self.tabBigSingleTransactionData = QtGui.QWidget()
        self.tabBigSingleTransactionData.setObjectName(_fromUtf8("tabBigSingleTransactionData"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabBigSingleTransactionData)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labStockCodeForBigSingleTransactionData = QtGui.QLabel(self.tabBigSingleTransactionData)
        self.labStockCodeForBigSingleTransactionData.setObjectName(_fromUtf8("labStockCodeForBigSingleTransactionData"))
        self.gridLayout_7.addWidget(self.labStockCodeForBigSingleTransactionData, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEditStockCodeForBigSingleTransactionData = QtGui.QLineEdit(self.tabBigSingleTransactionData)
        self.lineEditStockCodeForBigSingleTransactionData.setObjectName(_fromUtf8("lineEditStockCodeForBigSingleTransactionData"))
        self.horizontalLayout_8.addWidget(self.lineEditStockCodeForBigSingleTransactionData)
        self.chkBoxBulkModeForBigSingleTransactionData = QtGui.QCheckBox(self.tabBigSingleTransactionData)
        self.chkBoxBulkModeForBigSingleTransactionData.setObjectName(_fromUtf8("chkBoxBulkModeForBigSingleTransactionData"))
        self.horizontalLayout_8.addWidget(self.chkBoxBulkModeForBigSingleTransactionData)
        self.btnBulkModeForBigSingleTransactionData = QtGui.QPushButton(self.tabBigSingleTransactionData)
        self.btnBulkModeForBigSingleTransactionData.setObjectName(_fromUtf8("btnBulkModeForBigSingleTransactionData"))
        self.horizontalLayout_8.addWidget(self.btnBulkModeForBigSingleTransactionData)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.labTransactionTimeForBigSingleTransactionData = QtGui.QLabel(self.tabBigSingleTransactionData)
        self.labTransactionTimeForBigSingleTransactionData.setObjectName(_fromUtf8("labTransactionTimeForBigSingleTransactionData"))
        self.gridLayout_7.addWidget(self.labTransactionTimeForBigSingleTransactionData, 1, 0, 1, 1)
        self.lineEditTransactionTimeForBigSingleTransactionData = LineEdit(self.tabBigSingleTransactionData)
        self.lineEditTransactionTimeForBigSingleTransactionData.setObjectName(_fromUtf8("lineEditTransactionTimeForBigSingleTransactionData"))
        self.gridLayout_7.addWidget(self.lineEditTransactionTimeForBigSingleTransactionData, 1, 1, 1, 1)
        self.labLots = QtGui.QLabel(self.tabBigSingleTransactionData)
        self.labLots.setObjectName(_fromUtf8("labLots"))
        self.gridLayout_7.addWidget(self.labLots, 2, 0, 1, 1)
        self.lineEditLots = LineEdit(self.tabBigSingleTransactionData)
        self.lineEditLots.setObjectName(_fromUtf8("lineEditLots"))
        self.gridLayout_7.addWidget(self.lineEditLots, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.widgetBigSingleTransactionData = QtGui.QWidget(self.tabBigSingleTransactionData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetBigSingleTransactionData.sizePolicy().hasHeightForWidth())
        self.widgetBigSingleTransactionData.setSizePolicy(sizePolicy)
        self.widgetBigSingleTransactionData.setObjectName(_fromUtf8("widgetBigSingleTransactionData"))
        self.verticalLayout_8.addWidget(self.widgetBigSingleTransactionData)
        self.tabWidget.addTab(self.tabBigSingleTransactionData, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnShowData = QtGui.QPushButton(stockDataWidget)
        self.btnShowData.setObjectName(_fromUtf8("btnShowData"))
        self.horizontalLayout.addWidget(self.btnShowData)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSaveToCSV = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToCSV.setObjectName(_fromUtf8("btnSaveToCSV"))
        self.horizontalLayout.addWidget(self.btnSaveToCSV)
        self.btnSaveToExcel = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToExcel.setObjectName(_fromUtf8("btnSaveToExcel"))
        self.horizontalLayout.addWidget(self.btnSaveToExcel)
        self.btnSaveToHDF5 = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToHDF5.setObjectName(_fromUtf8("btnSaveToHDF5"))
        self.horizontalLayout.addWidget(self.btnSaveToHDF5)
        self.btnSaveToJSON = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToJSON.setObjectName(_fromUtf8("btnSaveToJSON"))
        self.horizontalLayout.addWidget(self.btnSaveToJSON)
        self.btnSaveToMySQL = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToMySQL.setObjectName(_fromUtf8("btnSaveToMySQL"))
        self.horizontalLayout.addWidget(self.btnSaveToMySQL)
        self.btnSaveToMongoDB = QtGui.QPushButton(stockDataWidget)
        self.btnSaveToMongoDB.setObjectName(_fromUtf8("btnSaveToMongoDB"))
        self.horizontalLayout.addWidget(self.btnSaveToMongoDB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(stockDataWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(stockDataWidget)

    def retranslateUi(self, stockDataWidget):
        stockDataWidget.setWindowTitle(_translate("stockDataWidget", "股票数据", None))
        self.labDataSource.setText(_translate("stockDataWidget", "数据源：", None))
        self.chkBoxSH.setText(_translate("stockDataWidget", "上证指数", None))
        self.chkBoxSZ.setText(_translate("stockDataWidget", "深圳成指", None))
        self.chkBoxHS300.setText(_translate("stockDataWidget", "沪深300", None))
        self.chkBoxSZ50.setText(_translate("stockDataWidget", "上证50", None))
        self.chkBoxZXB.setText(_translate("stockDataWidget", "中小板", None))
        self.chkBoxCYB.setText(_translate("stockDataWidget", "创业板", None))
        self.chkBoxStockCode.setText(_translate("stockDataWidget", "股票代码", None))
        self.labStockCodeForHistoricalQuotation.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForHistoricalQuotation.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForHistoricalQuotation.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.labStartTimeForHistoricalQuotation.setText(_translate("stockDataWidget", "开始时间：", None))
        self.labEndTimeForHistoricalQuotation.setText(_translate("stockDataWidget", "结束时间：", None))
        self.labDataType.setText(_translate("stockDataWidget", "数据类型：", None))
        self.comboBoxDataType.setItemText(0, _translate("stockDataWidget", "日K线", None))
        self.comboBoxDataType.setItemText(1, _translate("stockDataWidget", "每周", None))
        self.comboBoxDataType.setItemText(2, _translate("stockDataWidget", "每月", None))
        self.comboBoxDataType.setItemText(3, _translate("stockDataWidget", "5分钟", None))
        self.comboBoxDataType.setItemText(4, _translate("stockDataWidget", "15分钟", None))
        self.comboBoxDataType.setItemText(5, _translate("stockDataWidget", "30分钟", None))
        self.comboBoxDataType.setItemText(6, _translate("stockDataWidget", "60分钟", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistoricalQuotation), _translate("stockDataWidget", "历史行情", None))
        self.labStockCodeForRehabilitationData.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForRehabilitationData.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForRehabilitationData.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.labStartTimeForRehabilitationData.setText(_translate("stockDataWidget", "开始时间：", None))
        self.labEndTimeForRehabilitationData.setText(_translate("stockDataWidget", "结束时间：", None))
        self.labRehabilitationType.setText(_translate("stockDataWidget", "复权类型：", None))
        self.comboBoxRehabilitationType.setItemText(0, _translate("stockDataWidget", "前复权", None))
        self.comboBoxRehabilitationType.setItemText(1, _translate("stockDataWidget", "后复权", None))
        self.comboBoxRehabilitationType.setItemText(2, _translate("stockDataWidget", "不复权", None))
        self.labIsMarketIndex.setText(_translate("stockDataWidget", "是否为大盘指数：", None))
        self.chkBoxYes.setText(_translate("stockDataWidget", "是", None))
        self.chkBoxNo.setText(_translate("stockDataWidget", "否", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRehabilitationData), _translate("stockDataWidget", "复权数据", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRealTimeQuotes), _translate("stockDataWidget", "实时行情", None))
        self.labStockCodeForHistoricalTick.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForHistoricalTick.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForHistoricalTick.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.labTickTimeForHistoricalTick.setText(_translate("stockDataWidget", "分笔日期：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistoricalTick), _translate("stockDataWidget", "历史分笔", None))
        self.labDataSourceForRealTimeTick.setText(_translate("stockDataWidget", "数据源：", None))
        self.chkBoxSHForRealTimeTick.setText(_translate("stockDataWidget", "上证指数", None))
        self.chkBoxSZForRealTimeTick.setText(_translate("stockDataWidget", "深圳成指", None))
        self.chkBoxHS300ForRealTimeTick.setText(_translate("stockDataWidget", "沪深300", None))
        self.chkBoxSZ50ForRealTimeTick.setText(_translate("stockDataWidget", "上证50", None))
        self.chkBoxZXBForRealTimeTick.setText(_translate("stockDataWidget", "中小板", None))
        self.chkBoxCYBForRealTimeTick.setText(_translate("stockDataWidget", "创业板", None))
        self.chkBoxStockCodeForRealTimeTick.setText(_translate("stockDataWidget", "股票代码", None))
        self.labStockCodeForRealTimeTick.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForRealTimeTick.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForRealTimeTick.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRealTimeTick), _translate("stockDataWidget", "实时分笔", None))
        self.labStockCodeForSameDayHistoricalTick.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForSameDayHistoricalTick.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForSameDayHistoricalTick.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSameDayHistoricalTick), _translate("stockDataWidget", "当日历史分笔", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMarketIndexList), _translate("stockDataWidget", "大盘指数行情列表", None))
        self.labStockCodeForBigSingleTransactionData.setText(_translate("stockDataWidget", "股票代码：", None))
        self.chkBoxBulkModeForBigSingleTransactionData.setText(_translate("stockDataWidget", "批量模式", None))
        self.btnBulkModeForBigSingleTransactionData.setText(_translate("stockDataWidget", "批量数据导入", None))
        self.labTransactionTimeForBigSingleTransactionData.setText(_translate("stockDataWidget", "交易日期：", None))
        self.labLots.setText(_translate("stockDataWidget", "手数：", None))
        self.lineEditLots.setText(_translate("stockDataWidget", "400", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBigSingleTransactionData), _translate("stockDataWidget", "大单交易数据", None))
        self.btnShowData.setText(_translate("stockDataWidget", "抓取并显示数据", None))
        self.btnSaveToCSV.setText(_translate("stockDataWidget", "保存为CSV", None))
        self.btnSaveToExcel.setText(_translate("stockDataWidget", "保存为Excel", None))
        self.btnSaveToHDF5.setText(_translate("stockDataWidget", "保存为HDF5", None))
        self.btnSaveToJSON.setText(_translate("stockDataWidget", "保存为JSON", None))
        self.btnSaveToMySQL.setText(_translate("stockDataWidget", "保存至MySQL", None))
        self.btnSaveToMongoDB.setText(_translate("stockDataWidget", "保存至MongoDB", None))

from UiModule.common.commonTool.lineEdit import LineEdit
