# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transactionDataWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_transactionDataWidget(object):
    def setupUi(self, transactionDataWidget):
        transactionDataWidget.setObjectName("transactionDataWidget")
        transactionDataWidget.resize(692, 431)
        self.verticalLayout = QtWidgets.QVBoxLayout(transactionDataWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(transactionDataWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHistoricalQuotation = QtWidgets.QWidget()
        self.tabHistoricalQuotation.setObjectName("tabHistoricalQuotation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabHistoricalQuotation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labDataSource = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labDataSource.setObjectName("labDataSource")
        self.gridLayout_2.addWidget(self.labDataSource, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chkBoxSH = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSH.setObjectName("chkBoxSH")
        self.buttonGroup = QtWidgets.QButtonGroup(transactionDataWidget)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.chkBoxSH)
        self.gridLayout.addWidget(self.chkBoxSH, 0, 0, 1, 1)
        self.chkBoxSZ = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSZ.setObjectName("chkBoxSZ")
        self.buttonGroup.addButton(self.chkBoxSZ)
        self.gridLayout.addWidget(self.chkBoxSZ, 0, 1, 1, 1)
        self.chkBoxHS300 = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxHS300.setObjectName("chkBoxHS300")
        self.buttonGroup.addButton(self.chkBoxHS300)
        self.gridLayout.addWidget(self.chkBoxHS300, 0, 2, 1, 1)
        self.chkBoxSZ50 = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxSZ50.setObjectName("chkBoxSZ50")
        self.buttonGroup.addButton(self.chkBoxSZ50)
        self.gridLayout.addWidget(self.chkBoxSZ50, 0, 3, 1, 1)
        self.chkBoxZXB = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxZXB.setObjectName("chkBoxZXB")
        self.buttonGroup.addButton(self.chkBoxZXB)
        self.gridLayout.addWidget(self.chkBoxZXB, 1, 0, 1, 1)
        self.chkBoxCYB = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxCYB.setObjectName("chkBoxCYB")
        self.buttonGroup.addButton(self.chkBoxCYB)
        self.gridLayout.addWidget(self.chkBoxCYB, 1, 1, 1, 1)
        self.chkBoxStockCode = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxStockCode.setObjectName("chkBoxStockCode")
        self.buttonGroup.addButton(self.chkBoxStockCode)
        self.gridLayout.addWidget(self.chkBoxStockCode, 1, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.labStockCodeForHistoricalQuotation = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labStockCodeForHistoricalQuotation.setObjectName("labStockCodeForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.labStockCodeForHistoricalQuotation, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditStockCodeForHistoricalQuotation = QtWidgets.QLineEdit(self.tabHistoricalQuotation)
        self.lineEditStockCodeForHistoricalQuotation.setObjectName("lineEditStockCodeForHistoricalQuotation")
        self.horizontalLayout_2.addWidget(self.lineEditStockCodeForHistoricalQuotation)
        self.chkBoxBulkModeForHistoricalQuotation = QtWidgets.QCheckBox(self.tabHistoricalQuotation)
        self.chkBoxBulkModeForHistoricalQuotation.setObjectName("chkBoxBulkModeForHistoricalQuotation")
        self.horizontalLayout_2.addWidget(self.chkBoxBulkModeForHistoricalQuotation)
        self.btnBulkModeForHistoricalQuotation = QtWidgets.QPushButton(self.tabHistoricalQuotation)
        self.btnBulkModeForHistoricalQuotation.setObjectName("btnBulkModeForHistoricalQuotation")
        self.horizontalLayout_2.addWidget(self.btnBulkModeForHistoricalQuotation)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.labStartTimeForHistoricalQuotation = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labStartTimeForHistoricalQuotation.setObjectName("labStartTimeForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.labStartTimeForHistoricalQuotation, 2, 0, 1, 1)
        self.lineEditStartTimeForHistoricalQuotation = LineEdit(self.tabHistoricalQuotation)
        self.lineEditStartTimeForHistoricalQuotation.setObjectName("lineEditStartTimeForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.lineEditStartTimeForHistoricalQuotation, 2, 1, 1, 1)
        self.labEndTimeForHistoricalQuotation = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labEndTimeForHistoricalQuotation.setObjectName("labEndTimeForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.labEndTimeForHistoricalQuotation, 3, 0, 1, 1)
        self.lineEditEndTimeForHistoricalQuotation = LineEdit(self.tabHistoricalQuotation)
        self.lineEditEndTimeForHistoricalQuotation.setObjectName("lineEditEndTimeForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.lineEditEndTimeForHistoricalQuotation, 3, 1, 1, 1)
        self.labDataType = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labDataType.setObjectName("labDataType")
        self.gridLayout_2.addWidget(self.labDataType, 4, 0, 1, 1)
        self.comboBoxDataType = QtWidgets.QComboBox(self.tabHistoricalQuotation)
        self.comboBoxDataType.setObjectName("comboBoxDataType")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.comboBoxDataType.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxDataType, 4, 1, 1, 1)
        self.labSavePathForHistoricalQuotation = QtWidgets.QLabel(self.tabHistoricalQuotation)
        self.labSavePathForHistoricalQuotation.setObjectName("labSavePathForHistoricalQuotation")
        self.gridLayout_2.addWidget(self.labSavePathForHistoricalQuotation, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEditSavePathForHistoricalQuotation = LineEdit(self.tabHistoricalQuotation)
        self.lineEditSavePathForHistoricalQuotation.setObjectName("lineEditSavePathForHistoricalQuotation")
        self.horizontalLayout_9.addWidget(self.lineEditSavePathForHistoricalQuotation)
        self.btnSavePathForHistoricalQuotation = QtWidgets.QPushButton(self.tabHistoricalQuotation)
        self.btnSavePathForHistoricalQuotation.setObjectName("btnSavePathForHistoricalQuotation")
        self.horizontalLayout_9.addWidget(self.btnSavePathForHistoricalQuotation)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 5, 1, 1, 1)
        self.widgetHistoricalQuotation = QtWidgets.QWidget(self.tabHistoricalQuotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetHistoricalQuotation.sizePolicy().hasHeightForWidth())
        self.widgetHistoricalQuotation.setSizePolicy(sizePolicy)
        self.widgetHistoricalQuotation.setObjectName("widgetHistoricalQuotation")
        self.gridLayout_2.addWidget(self.widgetHistoricalQuotation, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tabHistoricalQuotation, "")
        self.tabRehabilitationData = QtWidgets.QWidget()
        self.tabRehabilitationData.setObjectName("tabRehabilitationData")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRehabilitationData)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labStockCodeForRehabilitationData = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labStockCodeForRehabilitationData.setObjectName("labStockCodeForRehabilitationData")
        self.gridLayout_3.addWidget(self.labStockCodeForRehabilitationData, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditStockCodeForRehabilitationData = QtWidgets.QLineEdit(self.tabRehabilitationData)
        self.lineEditStockCodeForRehabilitationData.setObjectName("lineEditStockCodeForRehabilitationData")
        self.horizontalLayout_3.addWidget(self.lineEditStockCodeForRehabilitationData)
        self.chkBoxBulkModeForRehabilitationData = QtWidgets.QCheckBox(self.tabRehabilitationData)
        self.chkBoxBulkModeForRehabilitationData.setObjectName("chkBoxBulkModeForRehabilitationData")
        self.horizontalLayout_3.addWidget(self.chkBoxBulkModeForRehabilitationData)
        self.btnBulkModeForRehabilitationData = QtWidgets.QPushButton(self.tabRehabilitationData)
        self.btnBulkModeForRehabilitationData.setObjectName("btnBulkModeForRehabilitationData")
        self.horizontalLayout_3.addWidget(self.btnBulkModeForRehabilitationData)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.labStartTimeForRehabilitationData = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labStartTimeForRehabilitationData.setObjectName("labStartTimeForRehabilitationData")
        self.gridLayout_3.addWidget(self.labStartTimeForRehabilitationData, 1, 0, 1, 1)
        self.lineEditStartTimeForRehabilitationData = LineEdit(self.tabRehabilitationData)
        self.lineEditStartTimeForRehabilitationData.setObjectName("lineEditStartTimeForRehabilitationData")
        self.gridLayout_3.addWidget(self.lineEditStartTimeForRehabilitationData, 1, 1, 1, 1)
        self.labEndTimeForRehabilitationData = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labEndTimeForRehabilitationData.setObjectName("labEndTimeForRehabilitationData")
        self.gridLayout_3.addWidget(self.labEndTimeForRehabilitationData, 2, 0, 1, 1)
        self.lineEditEndTimeForRehabilitationData = LineEdit(self.tabRehabilitationData)
        self.lineEditEndTimeForRehabilitationData.setObjectName("lineEditEndTimeForRehabilitationData")
        self.gridLayout_3.addWidget(self.lineEditEndTimeForRehabilitationData, 2, 1, 1, 1)
        self.labRehabilitationType = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labRehabilitationType.setObjectName("labRehabilitationType")
        self.gridLayout_3.addWidget(self.labRehabilitationType, 3, 0, 1, 1)
        self.comboBoxRehabilitationType = QtWidgets.QComboBox(self.tabRehabilitationData)
        self.comboBoxRehabilitationType.setObjectName("comboBoxRehabilitationType")
        self.comboBoxRehabilitationType.addItem("")
        self.comboBoxRehabilitationType.addItem("")
        self.comboBoxRehabilitationType.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxRehabilitationType, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkBoxYes = QtWidgets.QCheckBox(self.tabRehabilitationData)
        self.chkBoxYes.setObjectName("chkBoxYes")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(transactionDataWidget)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.chkBoxYes)
        self.horizontalLayout_4.addWidget(self.chkBoxYes)
        self.chkBoxNo = QtWidgets.QCheckBox(self.tabRehabilitationData)
        self.chkBoxNo.setObjectName("chkBoxNo")
        self.buttonGroup_2.addButton(self.chkBoxNo)
        self.horizontalLayout_4.addWidget(self.chkBoxNo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.labIsMarketIndex = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labIsMarketIndex.setObjectName("labIsMarketIndex")
        self.gridLayout_3.addWidget(self.labIsMarketIndex, 4, 0, 1, 1)
        self.labSavePathForRehabilitationData = QtWidgets.QLabel(self.tabRehabilitationData)
        self.labSavePathForRehabilitationData.setObjectName("labSavePathForRehabilitationData")
        self.gridLayout_3.addWidget(self.labSavePathForRehabilitationData, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEditSavePathForRehabilitationData = QtWidgets.QLineEdit(self.tabRehabilitationData)
        self.lineEditSavePathForRehabilitationData.setObjectName("lineEditSavePathForRehabilitationData")
        self.horizontalLayout_10.addWidget(self.lineEditSavePathForRehabilitationData)
        self.btnSavePathForRehabilitationData = QtWidgets.QPushButton(self.tabRehabilitationData)
        self.btnSavePathForRehabilitationData.setObjectName("btnSavePathForRehabilitationData")
        self.horizontalLayout_10.addWidget(self.btnSavePathForRehabilitationData)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.widgetRehabilitationData = QtWidgets.QWidget(self.tabRehabilitationData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRehabilitationData.sizePolicy().hasHeightForWidth())
        self.widgetRehabilitationData.setSizePolicy(sizePolicy)
        self.widgetRehabilitationData.setObjectName("widgetRehabilitationData")
        self.verticalLayout_3.addWidget(self.widgetRehabilitationData)
        self.tabWidget.addTab(self.tabRehabilitationData, "")
        self.tabRealTimeQuotes = QtWidgets.QWidget()
        self.tabRealTimeQuotes.setObjectName("tabRealTimeQuotes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabRealTimeQuotes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labSavePathForRealTimeQuotation = QtWidgets.QLabel(self.tabRealTimeQuotes)
        self.labSavePathForRealTimeQuotation.setObjectName("labSavePathForRealTimeQuotation")
        self.horizontalLayout_17.addWidget(self.labSavePathForRealTimeQuotation)
        self.lineEditSavePathForRealTimeQuotation = QtWidgets.QLineEdit(self.tabRealTimeQuotes)
        self.lineEditSavePathForRealTimeQuotation.setObjectName("lineEditSavePathForRealTimeQuotation")
        self.horizontalLayout_17.addWidget(self.lineEditSavePathForRealTimeQuotation)
        self.btnSavePathForRealTimeQuotation = QtWidgets.QPushButton(self.tabRealTimeQuotes)
        self.btnSavePathForRealTimeQuotation.setObjectName("btnSavePathForRealTimeQuotation")
        self.horizontalLayout_17.addWidget(self.btnSavePathForRealTimeQuotation)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.widgetRealTimeQuotes = QtWidgets.QWidget(self.tabRealTimeQuotes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRealTimeQuotes.sizePolicy().hasHeightForWidth())
        self.widgetRealTimeQuotes.setSizePolicy(sizePolicy)
        self.widgetRealTimeQuotes.setObjectName("widgetRealTimeQuotes")
        self.verticalLayout_4.addWidget(self.widgetRealTimeQuotes)
        self.tabWidget.addTab(self.tabRealTimeQuotes, "")
        self.tabHistoricalTick = QtWidgets.QWidget()
        self.tabHistoricalTick.setObjectName("tabHistoricalTick")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabHistoricalTick)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labStockCodeForHistoricalTick = QtWidgets.QLabel(self.tabHistoricalTick)
        self.labStockCodeForHistoricalTick.setObjectName("labStockCodeForHistoricalTick")
        self.gridLayout_4.addWidget(self.labStockCodeForHistoricalTick, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditStockCodeForHistoricalTick = QtWidgets.QLineEdit(self.tabHistoricalTick)
        self.lineEditStockCodeForHistoricalTick.setObjectName("lineEditStockCodeForHistoricalTick")
        self.horizontalLayout_6.addWidget(self.lineEditStockCodeForHistoricalTick)
        self.chkBoxBulkModeForHistoricalTick = QtWidgets.QCheckBox(self.tabHistoricalTick)
        self.chkBoxBulkModeForHistoricalTick.setObjectName("chkBoxBulkModeForHistoricalTick")
        self.horizontalLayout_6.addWidget(self.chkBoxBulkModeForHistoricalTick)
        self.btnBulkModeForHistoricalTick = QtWidgets.QPushButton(self.tabHistoricalTick)
        self.btnBulkModeForHistoricalTick.setObjectName("btnBulkModeForHistoricalTick")
        self.horizontalLayout_6.addWidget(self.btnBulkModeForHistoricalTick)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.labTickTimeForHistoricalTick = QtWidgets.QLabel(self.tabHistoricalTick)
        self.labTickTimeForHistoricalTick.setObjectName("labTickTimeForHistoricalTick")
        self.gridLayout_4.addWidget(self.labTickTimeForHistoricalTick, 1, 0, 1, 1)
        self.lineEditTickTimeForHistoricalTick = LineEdit(self.tabHistoricalTick)
        self.lineEditTickTimeForHistoricalTick.setObjectName("lineEditTickTimeForHistoricalTick")
        self.gridLayout_4.addWidget(self.lineEditTickTimeForHistoricalTick, 1, 1, 1, 1)
        self.labSavePathForHistoricalTick = QtWidgets.QLabel(self.tabHistoricalTick)
        self.labSavePathForHistoricalTick.setObjectName("labSavePathForHistoricalTick")
        self.gridLayout_4.addWidget(self.labSavePathForHistoricalTick, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEditSavePathForHistoricalTick = QtWidgets.QLineEdit(self.tabHistoricalTick)
        self.lineEditSavePathForHistoricalTick.setObjectName("lineEditSavePathForHistoricalTick")
        self.horizontalLayout_14.addWidget(self.lineEditSavePathForHistoricalTick)
        self.btnSavePathForHistoricalTick = QtWidgets.QPushButton(self.tabHistoricalTick)
        self.btnSavePathForHistoricalTick.setObjectName("btnSavePathForHistoricalTick")
        self.horizontalLayout_14.addWidget(self.btnSavePathForHistoricalTick)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.widgetHistoricalTick = QtWidgets.QWidget(self.tabHistoricalTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetHistoricalTick.sizePolicy().hasHeightForWidth())
        self.widgetHistoricalTick.setSizePolicy(sizePolicy)
        self.widgetHistoricalTick.setObjectName("widgetHistoricalTick")
        self.verticalLayout_5.addWidget(self.widgetHistoricalTick)
        self.tabWidget.addTab(self.tabHistoricalTick, "")
        self.tabRealTimeTick = QtWidgets.QWidget()
        self.tabRealTimeTick.setObjectName("tabRealTimeTick")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabRealTimeTick)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labDataSourceForRealTimeTick = QtWidgets.QLabel(self.tabRealTimeTick)
        self.labDataSourceForRealTimeTick.setObjectName("labDataSourceForRealTimeTick")
        self.gridLayout_6.addWidget(self.labDataSourceForRealTimeTick, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.chkBoxSHForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBoxSHForRealTimeTick.sizePolicy().hasHeightForWidth())
        self.chkBoxSHForRealTimeTick.setSizePolicy(sizePolicy)
        self.chkBoxSHForRealTimeTick.setObjectName("chkBoxSHForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxSHForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxSHForRealTimeTick, 0, 0, 1, 1)
        self.chkBoxSZForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBoxSZForRealTimeTick.sizePolicy().hasHeightForWidth())
        self.chkBoxSZForRealTimeTick.setSizePolicy(sizePolicy)
        self.chkBoxSZForRealTimeTick.setObjectName("chkBoxSZForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxSZForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxSZForRealTimeTick, 0, 1, 1, 1)
        self.chkBoxHS300ForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBoxHS300ForRealTimeTick.sizePolicy().hasHeightForWidth())
        self.chkBoxHS300ForRealTimeTick.setSizePolicy(sizePolicy)
        self.chkBoxHS300ForRealTimeTick.setObjectName("chkBoxHS300ForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxHS300ForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxHS300ForRealTimeTick, 0, 2, 1, 1)
        self.chkBoxSZ50ForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBoxSZ50ForRealTimeTick.sizePolicy().hasHeightForWidth())
        self.chkBoxSZ50ForRealTimeTick.setSizePolicy(sizePolicy)
        self.chkBoxSZ50ForRealTimeTick.setObjectName("chkBoxSZ50ForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxSZ50ForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxSZ50ForRealTimeTick, 0, 3, 1, 1)
        self.chkBoxZXBForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        self.chkBoxZXBForRealTimeTick.setObjectName("chkBoxZXBForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxZXBForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxZXBForRealTimeTick, 1, 0, 1, 1)
        self.chkBoxCYBForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        self.chkBoxCYBForRealTimeTick.setObjectName("chkBoxCYBForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxCYBForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxCYBForRealTimeTick, 1, 1, 1, 1)
        self.chkBoxStockCodeForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        self.chkBoxStockCodeForRealTimeTick.setObjectName("chkBoxStockCodeForRealTimeTick")
        self.buttonGroup_2.addButton(self.chkBoxStockCodeForRealTimeTick)
        self.gridLayout_5.addWidget(self.chkBoxStockCodeForRealTimeTick, 1, 2, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.labStockCodeForRealTimeTick = QtWidgets.QLabel(self.tabRealTimeTick)
        self.labStockCodeForRealTimeTick.setObjectName("labStockCodeForRealTimeTick")
        self.gridLayout_6.addWidget(self.labStockCodeForRealTimeTick, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditStockCodeForRealTimeTick = QtWidgets.QLineEdit(self.tabRealTimeTick)
        self.lineEditStockCodeForRealTimeTick.setObjectName("lineEditStockCodeForRealTimeTick")
        self.horizontalLayout_5.addWidget(self.lineEditStockCodeForRealTimeTick)
        self.chkBoxBulkModeForRealTimeTick = QtWidgets.QCheckBox(self.tabRealTimeTick)
        self.chkBoxBulkModeForRealTimeTick.setObjectName("chkBoxBulkModeForRealTimeTick")
        self.horizontalLayout_5.addWidget(self.chkBoxBulkModeForRealTimeTick)
        self.btnBulkModeForRealTimeTick = QtWidgets.QPushButton(self.tabRealTimeTick)
        self.btnBulkModeForRealTimeTick.setObjectName("btnBulkModeForRealTimeTick")
        self.horizontalLayout_5.addWidget(self.btnBulkModeForRealTimeTick)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.labSavePathForRealTimeTick = QtWidgets.QLabel(self.tabRealTimeTick)
        self.labSavePathForRealTimeTick.setObjectName("labSavePathForRealTimeTick")
        self.gridLayout_6.addWidget(self.labSavePathForRealTimeTick, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEditSavePathForRealTimeTick = QtWidgets.QLineEdit(self.tabRealTimeTick)
        self.lineEditSavePathForRealTimeTick.setObjectName("lineEditSavePathForRealTimeTick")
        self.horizontalLayout_13.addWidget(self.lineEditSavePathForRealTimeTick)
        self.btnSavePathForRealTimeTick = QtWidgets.QPushButton(self.tabRealTimeTick)
        self.btnSavePathForRealTimeTick.setObjectName("btnSavePathForRealTimeTick")
        self.horizontalLayout_13.addWidget(self.btnSavePathForRealTimeTick)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.widgetRealTimeTick = QtWidgets.QWidget(self.tabRealTimeTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetRealTimeTick.sizePolicy().hasHeightForWidth())
        self.widgetRealTimeTick.setSizePolicy(sizePolicy)
        self.widgetRealTimeTick.setObjectName("widgetRealTimeTick")
        self.verticalLayout_6.addWidget(self.widgetRealTimeTick)
        self.tabWidget.addTab(self.tabRealTimeTick, "")
        self.tabSameDayHistoricalTick = QtWidgets.QWidget()
        self.tabSameDayHistoricalTick.setObjectName("tabSameDayHistoricalTick")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabSameDayHistoricalTick)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labStockCodeForSameDayHistoricalTick = QtWidgets.QLabel(self.tabSameDayHistoricalTick)
        self.labStockCodeForSameDayHistoricalTick.setObjectName("labStockCodeForSameDayHistoricalTick")
        self.horizontalLayout_7.addWidget(self.labStockCodeForSameDayHistoricalTick)
        self.lineEditStockCodeForSameDayHistoricalTick = QtWidgets.QLineEdit(self.tabSameDayHistoricalTick)
        self.lineEditStockCodeForSameDayHistoricalTick.setObjectName("lineEditStockCodeForSameDayHistoricalTick")
        self.horizontalLayout_7.addWidget(self.lineEditStockCodeForSameDayHistoricalTick)
        self.chkBoxBulkModeForSameDayHistoricalTick = QtWidgets.QCheckBox(self.tabSameDayHistoricalTick)
        self.chkBoxBulkModeForSameDayHistoricalTick.setObjectName("chkBoxBulkModeForSameDayHistoricalTick")
        self.horizontalLayout_7.addWidget(self.chkBoxBulkModeForSameDayHistoricalTick)
        self.btnBulkModeForSameDayHistoricalTick = QtWidgets.QPushButton(self.tabSameDayHistoricalTick)
        self.btnBulkModeForSameDayHistoricalTick.setObjectName("btnBulkModeForSameDayHistoricalTick")
        self.horizontalLayout_7.addWidget(self.btnBulkModeForSameDayHistoricalTick)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labSavePathForSameDayHistoricalTick = QtWidgets.QLabel(self.tabSameDayHistoricalTick)
        self.labSavePathForSameDayHistoricalTick.setObjectName("labSavePathForSameDayHistoricalTick")
        self.horizontalLayout_12.addWidget(self.labSavePathForSameDayHistoricalTick)
        self.lineEditSavePathForSameDayHistoricalTick = QtWidgets.QLineEdit(self.tabSameDayHistoricalTick)
        self.lineEditSavePathForSameDayHistoricalTick.setObjectName("lineEditSavePathForSameDayHistoricalTick")
        self.horizontalLayout_12.addWidget(self.lineEditSavePathForSameDayHistoricalTick)
        self.btnSavePathForSameDayHistoricalTick = QtWidgets.QPushButton(self.tabSameDayHistoricalTick)
        self.btnSavePathForSameDayHistoricalTick.setObjectName("btnSavePathForSameDayHistoricalTick")
        self.horizontalLayout_12.addWidget(self.btnSavePathForSameDayHistoricalTick)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.widgetSameDayHistoricalTick = QtWidgets.QWidget(self.tabSameDayHistoricalTick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSameDayHistoricalTick.sizePolicy().hasHeightForWidth())
        self.widgetSameDayHistoricalTick.setSizePolicy(sizePolicy)
        self.widgetSameDayHistoricalTick.setObjectName("widgetSameDayHistoricalTick")
        self.verticalLayout_7.addWidget(self.widgetSameDayHistoricalTick)
        self.tabWidget.addTab(self.tabSameDayHistoricalTick, "")
        self.tabMarketIndexList = QtWidgets.QWidget()
        self.tabMarketIndexList.setObjectName("tabMarketIndexList")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabMarketIndexList)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widgetMarketIndexList = QtWidgets.QWidget(self.tabMarketIndexList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMarketIndexList.sizePolicy().hasHeightForWidth())
        self.widgetMarketIndexList.setSizePolicy(sizePolicy)
        self.widgetMarketIndexList.setObjectName("widgetMarketIndexList")
        self.gridLayout_8.addWidget(self.widgetMarketIndexList, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labSavePathForMarketIndexList = QtWidgets.QLabel(self.tabMarketIndexList)
        self.labSavePathForMarketIndexList.setObjectName("labSavePathForMarketIndexList")
        self.horizontalLayout_16.addWidget(self.labSavePathForMarketIndexList)
        self.lineEditSavePathForMarketIndexList = QtWidgets.QLineEdit(self.tabMarketIndexList)
        self.lineEditSavePathForMarketIndexList.setObjectName("lineEditSavePathForMarketIndexList")
        self.horizontalLayout_16.addWidget(self.lineEditSavePathForMarketIndexList)
        self.btnSavePathForMarketIndexList = QtWidgets.QPushButton(self.tabMarketIndexList)
        self.btnSavePathForMarketIndexList.setObjectName("btnSavePathForMarketIndexList")
        self.horizontalLayout_16.addWidget(self.btnSavePathForMarketIndexList)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMarketIndexList, "")
        self.tabBigSingleTransactionData = QtWidgets.QWidget()
        self.tabBigSingleTransactionData.setObjectName("tabBigSingleTransactionData")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabBigSingleTransactionData)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labStockCodeForBigSingleTransactionData = QtWidgets.QLabel(self.tabBigSingleTransactionData)
        self.labStockCodeForBigSingleTransactionData.setObjectName("labStockCodeForBigSingleTransactionData")
        self.gridLayout_7.addWidget(self.labStockCodeForBigSingleTransactionData, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditStockCodeForBigSingleTransactionData = QtWidgets.QLineEdit(self.tabBigSingleTransactionData)
        self.lineEditStockCodeForBigSingleTransactionData.setObjectName("lineEditStockCodeForBigSingleTransactionData")
        self.horizontalLayout_8.addWidget(self.lineEditStockCodeForBigSingleTransactionData)
        self.chkBoxBulkModeForBigSingleTransactionData = QtWidgets.QCheckBox(self.tabBigSingleTransactionData)
        self.chkBoxBulkModeForBigSingleTransactionData.setObjectName("chkBoxBulkModeForBigSingleTransactionData")
        self.horizontalLayout_8.addWidget(self.chkBoxBulkModeForBigSingleTransactionData)
        self.btnBulkModeForBigSingleTransactionData = QtWidgets.QPushButton(self.tabBigSingleTransactionData)
        self.btnBulkModeForBigSingleTransactionData.setObjectName("btnBulkModeForBigSingleTransactionData")
        self.horizontalLayout_8.addWidget(self.btnBulkModeForBigSingleTransactionData)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.labTransactionTimeForBigSingleTransactionData = QtWidgets.QLabel(self.tabBigSingleTransactionData)
        self.labTransactionTimeForBigSingleTransactionData.setObjectName("labTransactionTimeForBigSingleTransactionData")
        self.gridLayout_7.addWidget(self.labTransactionTimeForBigSingleTransactionData, 1, 0, 1, 1)
        self.lineEditTransactionTimeForBigSingleTransactionData = LineEdit(self.tabBigSingleTransactionData)
        self.lineEditTransactionTimeForBigSingleTransactionData.setObjectName("lineEditTransactionTimeForBigSingleTransactionData")
        self.gridLayout_7.addWidget(self.lineEditTransactionTimeForBigSingleTransactionData, 1, 1, 1, 1)
        self.labLots = QtWidgets.QLabel(self.tabBigSingleTransactionData)
        self.labLots.setObjectName("labLots")
        self.gridLayout_7.addWidget(self.labLots, 2, 0, 1, 1)
        self.lineEditLots = LineEdit(self.tabBigSingleTransactionData)
        self.lineEditLots.setObjectName("lineEditLots")
        self.gridLayout_7.addWidget(self.lineEditLots, 2, 1, 1, 1)
        self.labSavePathForBigSingleTransactionData = QtWidgets.QLabel(self.tabBigSingleTransactionData)
        self.labSavePathForBigSingleTransactionData.setObjectName("labSavePathForBigSingleTransactionData")
        self.gridLayout_7.addWidget(self.labSavePathForBigSingleTransactionData, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEditSavePathForBigSingleTransactionData = QtWidgets.QLineEdit(self.tabBigSingleTransactionData)
        self.lineEditSavePathForBigSingleTransactionData.setObjectName("lineEditSavePathForBigSingleTransactionData")
        self.horizontalLayout_11.addWidget(self.lineEditSavePathForBigSingleTransactionData)
        self.btnSavePathForBigSingleTransactionData = QtWidgets.QPushButton(self.tabBigSingleTransactionData)
        self.btnSavePathForBigSingleTransactionData.setObjectName("btnSavePathForBigSingleTransactionData")
        self.horizontalLayout_11.addWidget(self.btnSavePathForBigSingleTransactionData)
        self.gridLayout_7.addLayout(self.horizontalLayout_11, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.widgetBigSingleTransactionData = QtWidgets.QWidget(self.tabBigSingleTransactionData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetBigSingleTransactionData.sizePolicy().hasHeightForWidth())
        self.widgetBigSingleTransactionData.setSizePolicy(sizePolicy)
        self.widgetBigSingleTransactionData.setObjectName("widgetBigSingleTransactionData")
        self.verticalLayout_8.addWidget(self.widgetBigSingleTransactionData)
        self.tabWidget.addTab(self.tabBigSingleTransactionData, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnShowData = QtWidgets.QPushButton(transactionDataWidget)
        self.btnShowData.setObjectName("btnShowData")
        self.horizontalLayout.addWidget(self.btnShowData)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSaveToCSV = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToCSV.setObjectName("btnSaveToCSV")
        self.horizontalLayout.addWidget(self.btnSaveToCSV)
        self.btnSaveToExcel = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToExcel.setObjectName("btnSaveToExcel")
        self.horizontalLayout.addWidget(self.btnSaveToExcel)
        self.btnSaveToHDF5 = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToHDF5.setObjectName("btnSaveToHDF5")
        self.horizontalLayout.addWidget(self.btnSaveToHDF5)
        self.btnSaveToJSON = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToJSON.setObjectName("btnSaveToJSON")
        self.horizontalLayout.addWidget(self.btnSaveToJSON)
        self.btnSaveToMySQL = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToMySQL.setObjectName("btnSaveToMySQL")
        self.horizontalLayout.addWidget(self.btnSaveToMySQL)
        self.btnSaveToMongoDB = QtWidgets.QPushButton(transactionDataWidget)
        self.btnSaveToMongoDB.setObjectName("btnSaveToMongoDB")
        self.horizontalLayout.addWidget(self.btnSaveToMongoDB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(transactionDataWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(transactionDataWidget)

    def retranslateUi(self, transactionDataWidget):
        _translate = QtCore.QCoreApplication.translate
        transactionDataWidget.setWindowTitle(_translate("transactionDataWidget", "股票数据"))
        self.labDataSource.setText(_translate("transactionDataWidget", "数据源："))
        self.chkBoxSH.setText(_translate("transactionDataWidget", "上证指数"))
        self.chkBoxSZ.setText(_translate("transactionDataWidget", "深圳成指"))
        self.chkBoxHS300.setText(_translate("transactionDataWidget", "沪深300"))
        self.chkBoxSZ50.setText(_translate("transactionDataWidget", "上证50"))
        self.chkBoxZXB.setText(_translate("transactionDataWidget", "中小板"))
        self.chkBoxCYB.setText(_translate("transactionDataWidget", "创业板"))
        self.chkBoxStockCode.setText(_translate("transactionDataWidget", "股票代码"))
        self.labStockCodeForHistoricalQuotation.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForHistoricalQuotation.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForHistoricalQuotation.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labStartTimeForHistoricalQuotation.setText(_translate("transactionDataWidget", "开始时间："))
        self.labEndTimeForHistoricalQuotation.setText(_translate("transactionDataWidget", "结束时间："))
        self.labDataType.setText(_translate("transactionDataWidget", "数据类型："))
        self.comboBoxDataType.setItemText(0, _translate("transactionDataWidget", "日K线"))
        self.comboBoxDataType.setItemText(1, _translate("transactionDataWidget", "每周"))
        self.comboBoxDataType.setItemText(2, _translate("transactionDataWidget", "每月"))
        self.comboBoxDataType.setItemText(3, _translate("transactionDataWidget", "5分钟"))
        self.comboBoxDataType.setItemText(4, _translate("transactionDataWidget", "15分钟"))
        self.comboBoxDataType.setItemText(5, _translate("transactionDataWidget", "30分钟"))
        self.comboBoxDataType.setItemText(6, _translate("transactionDataWidget", "60分钟"))
        self.labSavePathForHistoricalQuotation.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForHistoricalQuotation.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistoricalQuotation), _translate("transactionDataWidget", "历史行情"))
        self.labStockCodeForRehabilitationData.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForRehabilitationData.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForRehabilitationData.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labStartTimeForRehabilitationData.setText(_translate("transactionDataWidget", "开始时间："))
        self.labEndTimeForRehabilitationData.setText(_translate("transactionDataWidget", "结束时间："))
        self.labRehabilitationType.setText(_translate("transactionDataWidget", "复权类型："))
        self.comboBoxRehabilitationType.setItemText(0, _translate("transactionDataWidget", "前复权"))
        self.comboBoxRehabilitationType.setItemText(1, _translate("transactionDataWidget", "后复权"))
        self.comboBoxRehabilitationType.setItemText(2, _translate("transactionDataWidget", "不复权"))
        self.chkBoxYes.setText(_translate("transactionDataWidget", "是"))
        self.chkBoxNo.setText(_translate("transactionDataWidget", "否"))
        self.labIsMarketIndex.setText(_translate("transactionDataWidget", "是否为大盘指数："))
        self.labSavePathForRehabilitationData.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForRehabilitationData.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRehabilitationData), _translate("transactionDataWidget", "复权数据"))
        self.labSavePathForRealTimeQuotation.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForRealTimeQuotation.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRealTimeQuotes), _translate("transactionDataWidget", "实时行情"))
        self.labStockCodeForHistoricalTick.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForHistoricalTick.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForHistoricalTick.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labTickTimeForHistoricalTick.setText(_translate("transactionDataWidget", "分笔日期："))
        self.labSavePathForHistoricalTick.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForHistoricalTick.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistoricalTick), _translate("transactionDataWidget", "历史分笔"))
        self.labDataSourceForRealTimeTick.setText(_translate("transactionDataWidget", "数据源："))
        self.chkBoxSHForRealTimeTick.setText(_translate("transactionDataWidget", "上证指数"))
        self.chkBoxSZForRealTimeTick.setText(_translate("transactionDataWidget", "深圳成指"))
        self.chkBoxHS300ForRealTimeTick.setText(_translate("transactionDataWidget", "沪深300"))
        self.chkBoxSZ50ForRealTimeTick.setText(_translate("transactionDataWidget", "上证50"))
        self.chkBoxZXBForRealTimeTick.setText(_translate("transactionDataWidget", "中小板"))
        self.chkBoxCYBForRealTimeTick.setText(_translate("transactionDataWidget", "创业板"))
        self.chkBoxStockCodeForRealTimeTick.setText(_translate("transactionDataWidget", "股票代码"))
        self.labStockCodeForRealTimeTick.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForRealTimeTick.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForRealTimeTick.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labSavePathForRealTimeTick.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForRealTimeTick.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRealTimeTick), _translate("transactionDataWidget", "实时分笔"))
        self.labStockCodeForSameDayHistoricalTick.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForSameDayHistoricalTick.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForSameDayHistoricalTick.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labSavePathForSameDayHistoricalTick.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForSameDayHistoricalTick.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSameDayHistoricalTick), _translate("transactionDataWidget", "当日历史分笔"))
        self.labSavePathForMarketIndexList.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForMarketIndexList.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMarketIndexList), _translate("transactionDataWidget", "大盘指数行情列表"))
        self.labStockCodeForBigSingleTransactionData.setText(_translate("transactionDataWidget", "股票代码："))
        self.chkBoxBulkModeForBigSingleTransactionData.setText(_translate("transactionDataWidget", "批量模式"))
        self.btnBulkModeForBigSingleTransactionData.setText(_translate("transactionDataWidget", "批量数据导入"))
        self.labTransactionTimeForBigSingleTransactionData.setText(_translate("transactionDataWidget", "交易日期："))
        self.labLots.setText(_translate("transactionDataWidget", "手数："))
        self.lineEditLots.setText(_translate("transactionDataWidget", "400"))
        self.labSavePathForBigSingleTransactionData.setText(_translate("transactionDataWidget", "保存路径："))
        self.btnSavePathForBigSingleTransactionData.setText(_translate("transactionDataWidget", "选择路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBigSingleTransactionData), _translate("transactionDataWidget", "大单交易数据"))
        self.btnShowData.setText(_translate("transactionDataWidget", "抓取并显示数据"))
        self.btnSaveToCSV.setText(_translate("transactionDataWidget", "保存为CSV"))
        self.btnSaveToExcel.setText(_translate("transactionDataWidget", "保存为Excel"))
        self.btnSaveToHDF5.setText(_translate("transactionDataWidget", "保存为HDF5"))
        self.btnSaveToJSON.setText(_translate("transactionDataWidget", "保存为JSON"))
        self.btnSaveToMySQL.setText(_translate("transactionDataWidget", "保存至MySQL"))
        self.btnSaveToMongoDB.setText(_translate("transactionDataWidget", "保存至MongoDB"))

from UiModule.common.commonTool.lineEdit import LineEdit
