# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 409)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuStrategyCenter = QtWidgets.QMenu(self.menubar)
        self.menuStrategyCenter.setObjectName("menuStrategyCenter")
        self.menuNewStrategy = QtWidgets.QMenu(self.menuStrategyCenter)
        self.menuNewStrategy.setObjectName("menuNewStrategy")
        self.menuTestStimulate = QtWidgets.QMenu(self.menubar)
        self.menuTestStimulate.setObjectName("menuTestStimulate")
        self.menuRealTrade = QtWidgets.QMenu(self.menubar)
        self.menuRealTrade.setObjectName("menuRealTrade")
        self.menuDateCenter = QtWidgets.QMenu(self.menubar)
        self.menuDateCenter.setObjectName("menuDateCenter")
        self.menuStockData = QtWidgets.QMenu(self.menuDateCenter)
        self.menuStockData.setObjectName("menuStockData")
        self.menuResearchReport = QtWidgets.QMenu(self.menubar)
        self.menuResearchReport.setObjectName("menuResearchReport")
        self.menuGetHelp = QtWidgets.QMenu(self.menubar)
        self.menuGetHelp.setObjectName("menuGetHelp")
        self.menuAssetsManager = QtWidgets.QMenu(self.menubar)
        self.menuAssetsManager.setObjectName("menuAssetsManager")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionStockStimulate = QtWidgets.QAction(mainWindow)
        self.actionStockStimulate.setObjectName("actionStockStimulate")
        self.actionFuturesStimulate = QtWidgets.QAction(mainWindow)
        self.actionFuturesStimulate.setObjectName("actionFuturesStimulate")
        self.actionFactorInvestment = QtWidgets.QAction(mainWindow)
        self.actionFactorInvestment.setObjectName("actionFactorInvestment")
        self.actionGuideCenter = QtWidgets.QAction(mainWindow)
        self.actionGuideCenter.setObjectName("actionGuideCenter")
        self.actionResearchReporting = QtWidgets.QAction(mainWindow)
        self.actionResearchReporting.setObjectName("actionResearchReporting")
        self.actionAboutSelf = QtWidgets.QAction(mainWindow)
        self.actionAboutSelf.setObjectName("actionAboutSelf")
        self.actionAssetsManager = QtWidgets.QAction(mainWindow)
        self.actionAssetsManager.setObjectName("actionAssetsManager")
        self.actionRealTrading = QtWidgets.QAction(mainWindow)
        self.actionRealTrading.setObjectName("actionRealTrading")
        self.actionStrategyMgr = QtWidgets.QAction(mainWindow)
        self.actionStrategyMgr.setObjectName("actionStrategyMgr")
        self.actionfuturesDate = QtWidgets.QAction(mainWindow)
        self.actionfuturesDate.setObjectName("actionfuturesDate")
        self.actionEditStrategy = QtWidgets.QAction(mainWindow)
        self.actionEditStrategy.setObjectName("actionEditStrategy")
        self.actionPieceStrategy = QtWidgets.QAction(mainWindow)
        self.actionPieceStrategy.setObjectName("actionPieceStrategy")
        self.actionTransactionData = QtWidgets.QAction(mainWindow)
        self.actionTransactionData.setObjectName("actionTransactionData")
        self.actionInvestRefData = QtWidgets.QAction(mainWindow)
        self.actionInvestRefData.setObjectName("actionInvestRefData")
        self.actionStockClassificationData = QtWidgets.QAction(mainWindow)
        self.actionStockClassificationData.setObjectName("actionStockClassificationData")
        self.actionBasicData = QtWidgets.QAction(mainWindow)
        self.actionBasicData.setObjectName("actionBasicData")
        self.actionMacroEconomicData = QtWidgets.QAction(mainWindow)
        self.actionMacroEconomicData.setObjectName("actionMacroEconomicData")
        self.actionNewEventData = QtWidgets.QAction(mainWindow)
        self.actionNewEventData.setObjectName("actionNewEventData")
        self.actionDragonTigerData = QtWidgets.QAction(mainWindow)
        self.actionDragonTigerData.setObjectName("actionDragonTigerData")
        self.actionShanghaiInterbankOfferedRate = QtWidgets.QAction(mainWindow)
        self.actionShanghaiInterbankOfferedRate.setObjectName("actionShanghaiInterbankOfferedRate")
        self.actionSetMySQL = QtWidgets.QAction(mainWindow)
        self.actionSetMySQL.setObjectName("actionSetMySQL")
        self.actionSetMongoDB = QtWidgets.QAction(mainWindow)
        self.actionSetMongoDB.setObjectName("actionSetMongoDB")
        self.menuNewStrategy.addAction(self.actionEditStrategy)
        self.menuNewStrategy.addAction(self.actionPieceStrategy)
        self.menuStrategyCenter.addAction(self.actionStrategyMgr)
        self.menuStrategyCenter.addAction(self.menuNewStrategy.menuAction())
        self.menuTestStimulate.addAction(self.actionStockStimulate)
        self.menuTestStimulate.addAction(self.actionFuturesStimulate)
        self.menuRealTrade.addAction(self.actionRealTrading)
        self.menuStockData.addAction(self.actionTransactionData)
        self.menuStockData.addAction(self.actionInvestRefData)
        self.menuStockData.addAction(self.actionStockClassificationData)
        self.menuStockData.addAction(self.actionBasicData)
        self.menuStockData.addAction(self.actionMacroEconomicData)
        self.menuStockData.addAction(self.actionNewEventData)
        self.menuStockData.addAction(self.actionDragonTigerData)
        self.menuStockData.addAction(self.actionShanghaiInterbankOfferedRate)
        self.menuDateCenter.addAction(self.menuStockData.menuAction())
        self.menuDateCenter.addAction(self.actionfuturesDate)
        self.menuDateCenter.addAction(self.actionSetMySQL)
        self.menuDateCenter.addAction(self.actionSetMongoDB)
        self.menuResearchReport.addAction(self.actionResearchReporting)
        self.menuGetHelp.addAction(self.actionGuideCenter)
        self.menuGetHelp.addAction(self.actionAboutSelf)
        self.menuAssetsManager.addAction(self.actionAssetsManager)
        self.menubar.addAction(self.menuStrategyCenter.menuAction())
        self.menubar.addAction(self.menuDateCenter.menuAction())
        self.menubar.addAction(self.menuTestStimulate.menuAction())
        self.menubar.addAction(self.menuRealTrade.menuAction())
        self.menubar.addAction(self.menuAssetsManager.menuAction())
        self.menubar.addAction(self.menuResearchReport.menuAction())
        self.menubar.addAction(self.menuGetHelp.menuAction())

        self.gridLayout_for_widget = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_for_widget.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_for_widget.setObjectName("gridLayout")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "量化分析"))
        self.menuStrategyCenter.setTitle(_translate("mainWindow", "策略中心"))
        self.menuNewStrategy.setTitle(_translate("mainWindow", "新建策略"))
        self.menuTestStimulate.setTitle(_translate("mainWindow", "回测模拟"))
        self.menuRealTrade.setTitle(_translate("mainWindow", "实盘交易"))
        self.menuDateCenter.setTitle(_translate("mainWindow", "数据中心"))
        self.menuStockData.setTitle(_translate("mainWindow", "股票数据"))
        self.menuResearchReport.setTitle(_translate("mainWindow", "行研报告"))
        self.menuGetHelp.setTitle(_translate("mainWindow", "获取帮助"))
        self.menuAssetsManager.setTitle(_translate("mainWindow", "资产管理"))
        self.actionStockStimulate.setText(_translate("mainWindow", "股票模拟"))
        self.actionFuturesStimulate.setText(_translate("mainWindow", "期货模拟"))
        self.actionFactorInvestment.setText(_translate("mainWindow", "因子投资"))
        self.actionGuideCenter.setText(_translate("mainWindow", "使用向导"))
        self.actionResearchReporting.setText(_translate("mainWindow", "行研报告"))
        self.actionAboutSelf.setText(_translate("mainWindow", "关于我们"))
        self.actionAssetsManager.setText(_translate("mainWindow", "资金账户管理"))
        self.actionRealTrading.setText(_translate("mainWindow", "实盘交易"))
        self.actionStrategyMgr.setText(_translate("mainWindow", "策略管理"))
        self.actionfuturesDate.setText(_translate("mainWindow", "期货数据"))
        self.actionEditStrategy.setText(_translate("mainWindow", "编写策略"))
        self.actionPieceStrategy.setText(_translate("mainWindow", "快速新建"))
        self.actionTransactionData.setText(_translate("mainWindow", "交易数据"))
        self.actionInvestRefData.setText(_translate("mainWindow", "投资参考数据"))
        self.actionStockClassificationData.setText(_translate("mainWindow", "股票分类数据"))
        self.actionBasicData.setText(_translate("mainWindow", "基本面数据"))
        self.actionMacroEconomicData.setText(_translate("mainWindow", "宏观经济数据"))
        self.actionNewEventData.setText(_translate("mainWindow", "新闻事件数据"))
        self.actionDragonTigerData.setText(_translate("mainWindow", "龙虎榜数据"))
        self.actionShanghaiInterbankOfferedRate.setText(_translate("mainWindow", "银行间同业拆放利率"))
        self.actionSetMySQL.setText(_translate("mainWindow", "配置MySQL"))
        self.actionSetMongoDB.setText(_translate("mainWindow", "配置MongoDB"))

