# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(800, 409)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuStrategyCenter = QtGui.QMenu(self.menubar)
        self.menuStrategyCenter.setObjectName(_fromUtf8("menuStrategyCenter"))
        self.menuNewStrategy = QtGui.QMenu(self.menuStrategyCenter)
        self.menuNewStrategy.setObjectName(_fromUtf8("menuNewStrategy"))
        self.menuTestStimulate = QtGui.QMenu(self.menubar)
        self.menuTestStimulate.setObjectName(_fromUtf8("menuTestStimulate"))
        self.menuRealTrade = QtGui.QMenu(self.menubar)
        self.menuRealTrade.setObjectName(_fromUtf8("menuRealTrade"))
        self.menuDateCenter = QtGui.QMenu(self.menubar)
        self.menuDateCenter.setObjectName(_fromUtf8("menuDateCenter"))
        self.menuStockData = QtGui.QMenu(self.menuDateCenter)
        self.menuStockData.setObjectName(_fromUtf8("menuStockData"))
        self.menuResearchReport = QtGui.QMenu(self.menubar)
        self.menuResearchReport.setObjectName(_fromUtf8("menuResearchReport"))
        self.menuGetHelp = QtGui.QMenu(self.menubar)
        self.menuGetHelp.setObjectName(_fromUtf8("menuGetHelp"))
        self.menuAssetsManager = QtGui.QMenu(self.menubar)
        self.menuAssetsManager.setObjectName(_fromUtf8("menuAssetsManager"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionStockStimulate = QtGui.QAction(mainWindow)
        self.actionStockStimulate.setObjectName(_fromUtf8("actionStockStimulate"))
        self.actionFuturesStimulate = QtGui.QAction(mainWindow)
        self.actionFuturesStimulate.setObjectName(_fromUtf8("actionFuturesStimulate"))
        self.actionFactorInvestment = QtGui.QAction(mainWindow)
        self.actionFactorInvestment.setObjectName(_fromUtf8("actionFactorInvestment"))
        self.actionGuideCenter = QtGui.QAction(mainWindow)
        self.actionGuideCenter.setObjectName(_fromUtf8("actionGuideCenter"))
        self.actionResearchReporting = QtGui.QAction(mainWindow)
        self.actionResearchReporting.setObjectName(_fromUtf8("actionResearchReporting"))
        self.actionAboutSelf = QtGui.QAction(mainWindow)
        self.actionAboutSelf.setObjectName(_fromUtf8("actionAboutSelf"))
        self.actionAssetsManager = QtGui.QAction(mainWindow)
        self.actionAssetsManager.setObjectName(_fromUtf8("actionAssetsManager"))
        self.actionRealTrading = QtGui.QAction(mainWindow)
        self.actionRealTrading.setObjectName(_fromUtf8("actionRealTrading"))
        self.actionStrategyMgr = QtGui.QAction(mainWindow)
        self.actionStrategyMgr.setObjectName(_fromUtf8("actionStrategyMgr"))
        self.actionfuturesDate = QtGui.QAction(mainWindow)
        self.actionfuturesDate.setObjectName(_fromUtf8("actionfuturesDate"))
        self.actionEditStrategy = QtGui.QAction(mainWindow)
        self.actionEditStrategy.setObjectName(_fromUtf8("actionEditStrategy"))
        self.actionPieceStrategy = QtGui.QAction(mainWindow)
        self.actionPieceStrategy.setObjectName(_fromUtf8("actionPieceStrategy"))
        self.actionTransactionData = QtGui.QAction(mainWindow)
        self.actionTransactionData.setObjectName(_fromUtf8("actionTransactionData"))
        self.actionInvestRefData = QtGui.QAction(mainWindow)
        self.actionInvestRefData.setObjectName(_fromUtf8("actionInvestRefData"))
        self.actionStockClassificationData = QtGui.QAction(mainWindow)
        self.actionStockClassificationData.setObjectName(_fromUtf8("actionStockClassificationData"))
        self.actionBasicData = QtGui.QAction(mainWindow)
        self.actionBasicData.setObjectName(_fromUtf8("actionBasicData"))
        self.actionMacroEconomicData = QtGui.QAction(mainWindow)
        self.actionMacroEconomicData.setObjectName(_fromUtf8("actionMacroEconomicData"))
        self.actionNewEventData = QtGui.QAction(mainWindow)
        self.actionNewEventData.setObjectName(_fromUtf8("actionNewEventData"))
        self.actionDragonTigerData = QtGui.QAction(mainWindow)
        self.actionDragonTigerData.setObjectName(_fromUtf8("actionDragonTigerData"))
        self.actionShanghaiInterbankOfferedRate = QtGui.QAction(mainWindow)
        self.actionShanghaiInterbankOfferedRate.setObjectName(_fromUtf8("actionShanghaiInterbankOfferedRate"))
        self.actionSetMySQL = QtGui.QAction(mainWindow)
        self.actionSetMySQL.setObjectName(_fromUtf8("actionSetMySQL"))
        self.actionSetMongoDB = QtGui.QAction(mainWindow)
        self.actionSetMongoDB.setObjectName(_fromUtf8("actionSetMongoDB"))
        self.menuNewStrategy.addAction(self.actionEditStrategy)
        self.menuNewStrategy.addAction(self.actionPieceStrategy)
        self.menuStrategyCenter.addAction(self.actionStrategyMgr)
        self.menuStrategyCenter.addAction(self.menuNewStrategy.menuAction())
        self.menuTestStimulate.addAction(self.actionStockStimulate)
        self.menuTestStimulate.addAction(self.actionFuturesStimulate)
        self.menuRealTrade.addAction(self.actionRealTrading)
        self.menuStockData.addAction(self.actionTransactionData)
        self.menuStockData.addAction(self.actionInvestRefData)
        self.menuStockData.addAction(self.actionStockClassificationData)
        self.menuStockData.addAction(self.actionBasicData)
        self.menuStockData.addAction(self.actionMacroEconomicData)
        self.menuStockData.addAction(self.actionNewEventData)
        self.menuStockData.addAction(self.actionDragonTigerData)
        self.menuStockData.addAction(self.actionShanghaiInterbankOfferedRate)
        self.menuDateCenter.addAction(self.menuStockData.menuAction())
        self.menuDateCenter.addAction(self.actionfuturesDate)
        self.menuDateCenter.addAction(self.actionSetMySQL)
        self.menuDateCenter.addAction(self.actionSetMongoDB)
        self.menuResearchReport.addAction(self.actionResearchReporting)
        self.menuGetHelp.addAction(self.actionGuideCenter)
        self.menuGetHelp.addAction(self.actionAboutSelf)
        self.menuAssetsManager.addAction(self.actionAssetsManager)
        self.menubar.addAction(self.menuStrategyCenter.menuAction())
        self.menubar.addAction(self.menuDateCenter.menuAction())
        self.menubar.addAction(self.menuTestStimulate.menuAction())
        self.menubar.addAction(self.menuRealTrade.menuAction())
        self.menubar.addAction(self.menuAssetsManager.menuAction())
        self.menubar.addAction(self.menuResearchReport.menuAction())
        self.menubar.addAction(self.menuGetHelp.menuAction())

        self.gridLayout_for_widget = QtGui.QGridLayout(self.widget)
        self.gridLayout_for_widget.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_for_widget.setObjectName(_fromUtf8("gridLayout"))

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "量化分析", None))
        self.menuStrategyCenter.setTitle(_translate("mainWindow", "策略中心", None))
        self.menuNewStrategy.setTitle(_translate("mainWindow", "新建策略", None))
        self.menuTestStimulate.setTitle(_translate("mainWindow", "回测模拟", None))
        self.menuRealTrade.setTitle(_translate("mainWindow", "实盘交易", None))
        self.menuDateCenter.setTitle(_translate("mainWindow", "数据中心", None))
        self.menuStockData.setTitle(_translate("mainWindow", "股票数据", None))
        self.menuResearchReport.setTitle(_translate("mainWindow", "行研报告", None))
        self.menuGetHelp.setTitle(_translate("mainWindow", "获取帮助", None))
        self.menuAssetsManager.setTitle(_translate("mainWindow", "资产管理", None))
        self.actionStockStimulate.setText(_translate("mainWindow", "股票模拟", None))
        self.actionFuturesStimulate.setText(_translate("mainWindow", "期货模拟", None))
        self.actionFactorInvestment.setText(_translate("mainWindow", "因子投资", None))
        self.actionGuideCenter.setText(_translate("mainWindow", "使用向导", None))
        self.actionResearchReporting.setText(_translate("mainWindow", "行研报告", None))
        self.actionAboutSelf.setText(_translate("mainWindow", "关于我们", None))
        self.actionAssetsManager.setText(_translate("mainWindow", "资金账户管理", None))
        self.actionRealTrading.setText(_translate("mainWindow", "实盘交易", None))
        self.actionStrategyMgr.setText(_translate("mainWindow", "策略管理", None))
        self.actionfuturesDate.setText(_translate("mainWindow", "期货数据", None))
        self.actionEditStrategy.setText(_translate("mainWindow", "编写策略", None))
        self.actionPieceStrategy.setText(_translate("mainWindow", "快速新建", None))
        self.actionTransactionData.setText(_translate("mainWindow", "交易数据", None))
        self.actionInvestRefData.setText(_translate("mainWindow", "投资参考数据", None))
        self.actionStockClassificationData.setText(_translate("mainWindow", "股票分类数据", None))
        self.actionBasicData.setText(_translate("mainWindow", "基本面数据", None))
        self.actionMacroEconomicData.setText(_translate("mainWindow", "宏观经济数据", None))
        self.actionNewEventData.setText(_translate("mainWindow", "新闻事件数据", None))
        self.actionDragonTigerData.setText(_translate("mainWindow", "龙虎榜数据", None))
        self.actionShanghaiInterbankOfferedRate.setText(_translate("mainWindow", "银行间同业拆放利率", None))
        self.actionSetMySQL.setText(_translate("mainWindow", "配置MySQL", None))
        self.actionSetMongoDB.setText(_translate("mainWindow", "配置MongoDB", None))

