# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'futuresDataWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_futureDataWidget(object):
    def setupUi(self, futureDataWidget):
        futureDataWidget.setObjectName("futureDataWidget")
        futureDataWidget.resize(1203, 810)
        self.verticalLayout = QtWidgets.QVBoxLayout(futureDataWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labDataSource = QtWidgets.QLabel(futureDataWidget)
        self.labDataSource.setObjectName("labDataSource")
        self.gridLayout.addWidget(self.labDataSource, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkBoxSH = QtWidgets.QCheckBox(futureDataWidget)
        self.chkBoxSH.setObjectName("chkBoxSH")
        self.horizontalLayout_3.addWidget(self.chkBoxSH)
        self.chkBoxSZ = QtWidgets.QCheckBox(futureDataWidget)
        self.chkBoxSZ.setObjectName("chkBoxSZ")
        self.horizontalLayout_3.addWidget(self.chkBoxSZ)
        self.chkBoxHS300 = QtWidgets.QCheckBox(futureDataWidget)
        self.chkBoxHS300.setObjectName("chkBoxHS300")
        self.horizontalLayout_3.addWidget(self.chkBoxHS300)
        self.chkBoxSZ50 = QtWidgets.QCheckBox(futureDataWidget)
        self.chkBoxSZ50.setObjectName("chkBoxSZ50")
        self.horizontalLayout_3.addWidget(self.chkBoxSZ50)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.labStartTime = QtWidgets.QLabel(futureDataWidget)
        self.labStartTime.setObjectName("labStartTime")
        self.gridLayout.addWidget(self.labStartTime, 1, 0, 1, 1)
        self.lineEditStartTime = LineEdit(futureDataWidget)
        self.lineEditStartTime.setObjectName("lineEditStartTime")
        self.gridLayout.addWidget(self.lineEditStartTime, 1, 1, 1, 1)
        self.labEndTime = QtWidgets.QLabel(futureDataWidget)
        self.labEndTime.setObjectName("labEndTime")
        self.gridLayout.addWidget(self.labEndTime, 2, 0, 1, 1)
        self.lineEditEndTime = LineEdit(futureDataWidget)
        self.lineEditEndTime.setObjectName("lineEditEndTime")
        self.gridLayout.addWidget(self.lineEditEndTime, 2, 1, 1, 1)
        self.labSavePath = QtWidgets.QLabel(futureDataWidget)
        self.labSavePath.setObjectName("labSavePath")
        self.gridLayout.addWidget(self.labSavePath, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditSavePath = LineEdit(futureDataWidget)
        self.lineEditSavePath.setObjectName("lineEditSavePath")
        self.horizontalLayout_2.addWidget(self.lineEditSavePath)
        self.btnSelectSavePath = QtWidgets.QPushButton(futureDataWidget)
        self.btnSelectSavePath.setObjectName("btnSelectSavePath")
        self.horizontalLayout_2.addWidget(self.btnSelectSavePath)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = QtWidgets.QWidget(futureDataWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSaveToCSV = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToCSV.setObjectName("btnSaveToCSV")
        self.horizontalLayout.addWidget(self.btnSaveToCSV)
        self.btnSaveToExcel = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToExcel.setObjectName("btnSaveToExcel")
        self.horizontalLayout.addWidget(self.btnSaveToExcel)
        self.btnSaveToHDF5 = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToHDF5.setObjectName("btnSaveToHDF5")
        self.horizontalLayout.addWidget(self.btnSaveToHDF5)
        self.btnSaveToJSON = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToJSON.setObjectName("btnSaveToJSON")
        self.horizontalLayout.addWidget(self.btnSaveToJSON)
        self.btnSaveToMySQL = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToMySQL.setObjectName("btnSaveToMySQL")
        self.horizontalLayout.addWidget(self.btnSaveToMySQL)
        self.btnSaveToMongoDB = QtWidgets.QPushButton(futureDataWidget)
        self.btnSaveToMongoDB.setObjectName("btnSaveToMongoDB")
        self.horizontalLayout.addWidget(self.btnSaveToMongoDB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(futureDataWidget)
        QtCore.QMetaObject.connectSlotsByName(futureDataWidget)

    def retranslateUi(self, futureDataWidget):
        _translate = QtCore.QCoreApplication.translate
        futureDataWidget.setWindowTitle(_translate("futureDataWidget", "期货数据"))
        self.labDataSource.setText(_translate("futureDataWidget", "数据源："))
        self.chkBoxSH.setText(_translate("futureDataWidget", "中金所"))
        self.chkBoxSZ.setText(_translate("futureDataWidget", "郑商所"))
        self.chkBoxHS300.setText(_translate("futureDataWidget", "上期所"))
        self.chkBoxSZ50.setText(_translate("futureDataWidget", "大商所"))
        self.labStartTime.setText(_translate("futureDataWidget", "开始时间："))
        self.labEndTime.setText(_translate("futureDataWidget", "结束时间："))
        self.labSavePath.setText(_translate("futureDataWidget", "保存路径："))
        self.btnSelectSavePath.setText(_translate("futureDataWidget", "选择路劲"))
        self.btnSaveToCSV.setText(_translate("futureDataWidget", "保存为CSV"))
        self.btnSaveToExcel.setText(_translate("futureDataWidget", "保存为Excel"))
        self.btnSaveToHDF5.setText(_translate("futureDataWidget", "保存为HDF5"))
        self.btnSaveToJSON.setText(_translate("futureDataWidget", "保存为JSON"))
        self.btnSaveToMySQL.setText(_translate("futureDataWidget", "保存至MySQL"))
        self.btnSaveToMongoDB.setText(_translate("futureDataWidget", "保存至MongoDB"))

from UiModule.common.commonTool.lineEdit import LineEdit
